name: Benchmark GitHub Runner

on:
  push:
    branches: [ main ]

jobs:
  benchmark:
    runs-on: [self-hosted, arm64]  # Use 'x86' label if it's your x86 VM
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Benchmark: Install + Sleep
        run: |
          echo "⏱️ Starting Benchmark..."
          start=$(date +%s)
          sudo apt update && sudo apt install -y curl
          sleep 5
          end=$(date +%s)
          echo "⏱️ Total Benchmark Duration: $((end - start)) seconds"

